#!/bin/sh
#echo "[debug.jzy] [01-wds] INTERFACE:$INTERFACE  ACTION:$ACTION" > /dev/console

len=${#INTERFACE}

if [ "${len}" = "8" ] || [ "${len}" = "9" ]; then

	result=$(echo "${INTERFACE}" | grep "wds[0-9]\.[0-9]\.[0-9]")

	if [ -n "${result}" ] && ([ "$ACTION" = "add" ] || [ "$ACTION" = "register" ]); then

		# Up the interface
		echo "[debug.jzy] ifconfig $INTERFACE up " > /dev/console
		ifconfig "$INTERFACE" up
			
		# Add the interface to bridge
		echo "[debug.jzy] brctl addif br-lan $INTERFACE" > /dev/console
		brctl addif br-lan "$INTERFACE"

		# Enable spanning tree protocol
		#echo "[debug.jzy] brctl stp br-lan on" > /dev/console
		#brctl stp br-lan on

		# Notify NAS of adding the interface
		echo "[debug.jzy] wl -i $INTERFACE wds_enable 1" > /dev/console
		wl -i "$INTERFACE" wds_enable 1
		wifi vlan "wdsup" "$INTERFACE"

	fi
fi
