#!/bin/sh

[ "$TYPE" = "neigh" -a "$ACTION" = "add" ] && {

	. /usr/share/libubox/jshn.sh
	json_init
	json_load "`ubus call network.interface.lan status`"
	json_get_var device device

	br_device="$(echo $EXTRA | awk '{print $1}')"
	neigh_item="$(echo $EXTRA | awk '{print $2,$3}')"

	if [ "$device" = "$br_device" ] ; then
		ubus call client_mgmt update "{\"report_neigh\":\"$neigh_item\"}"
	fi
}