#!/bin/sh

. /lib/functions.sh
. /lib/switch/core_phy.sh

# input : <mac>
# output: <wl ifname> or ""

local GMAC3_FWD0_PORT="5"
local GMAC3_FWD1_PORT="7"

output_ifname() {
	local ifname="$(config_get "$1" ifname)"
	local mac="$2"
	local out="$3"
	local assoclist
	
	[ -z "$ifname" ] && return 0;

	if [ "$DEFAULT_WLIFNAME" == "" ]
	then
			DEFAULT_WLIFNAME="$ifname"
	fi
	
	assoclist="$(wl -i "$ifname" assoclist 2>/dev/null)"
	if echo "$assoclist" | grep -q "$mac" ; then
		eval "${out}=\${${out}}\ ${ifname}"
#		eval "${out}=${ifname}"
	fi
}

gmac3_hwswitch_find_mac_port() {
	local mac="$1"
	mac="$(echo $mac | tr '[A-Z]' '[a-z]' | sed 's/://g')"
	echo -n $(echo "$(dump_arl_table)" | awk -F ' ' -v mac="$mac" '{if($1 == mac)print $3; break;}')
}


gmac3_dhd_get_ifname_by_mac() {
	local mac="$1"
	
	mac="$(echo $mac | tr '[a-z]' '[A-Z]')"
	config_load wireless
	config_foreach output_ifname "wifi-iface" "$mac" "WLIFNAME"
	
	if [ "$WLIFNAME" = "" ];
	then
		local port=$(gmac3_hwswitch_find_mac_port "$mac")
		if [ "$port" = "$GMAC3_FWD0_PORT" -o "$port" = "$GMAC3_FWD1_PORT" ];
		then
			WLIFNAME="$DEFAULT_WLIFNAME"
		fi
	fi 

	echo $WLIFNAME | awk -F' ' '{printf $1}'
}

[ $# != 1 ] && echo "" && exit 0

#gmac3_dhd_get_ifname_by_mac "$1"