#!/bin/sh

. /usr/share/libubox/jshn.sh

# start wps pbc
if [ "$(uci get meshd.meshd.enable)" == "on" -a "$(uci get meshd.meshd.role)" == "agent" ]; then
	local MSG=`ubus call map meshd '{"action": "get_backhaul_type"}'`
	#echo $MSG > /dev/console
	json_load "$MSG"
	json_get_var backhaul_type ret
	# backhaul_type=2 means agent is wired connetion
	if [ "$backhaul_type" == "2" ]; then
		echo "Agent hostapd wps-pbc start" > /dev/console
		hostapd_cli -i wl0.1 wps_pbc
		hostapd_cli -i wl1.1 wps_pbc
	else
		echo "Agent wps-pbc start" > /dev/console
		for dir in /var/run/*_wpa_supplicant; do
			[ -d "$dir" ] || continue
			wpa_cli -p "$dir" wps_pbc multi_ap=1
			pid=${dir}_event.pid
			[ -f $pid ] || {
				wpa_cli -p "$dir" -a/lib/wifi/wps-supplicant-event -P$pid -B 
			}
		done
	fi
elif [ "$(uci get meshd.meshd.enable)" == "on" -a "$(uci get meshd.meshd.role)" == "controller" ]; then
	hostapd_cli -i wl0.1 wps_pbc
	hostapd_cli -i wl1.1 wps_pbc
else
	if [ "$(nvram kget rftestflag)" == "1" -a "$(uci get factory.factorymode.enable)" != "yes" -a "$(uci get sysmode.sysmode.mode)" != "repeater" ]; then
		lua -e "require 'luci.controller.admin.wireless'.wireless_wps_connect({option = 'connect'})"
	else
		if [ ! -e /tmp/btn_check ];then
			echo 0 > /tmp/btn_check
		fi
		ret=$(cat /tmp/btn_check)
		ret=$(($ret | 0x8))
		echo $ret > /tmp/btn_check
	fi

fi
