#!/bin/sh

local release=$(uname -a)

[ "x$DEVNAME" == "x" ] && exit 0

$(echo "$DEVPATH" | grep -Eq ".*usb[1-3]$") || exit 0
 
case $ACTION in
	add)
		if $(echo $release | grep -Eq "2.6.36")
		then
#			[ -e /proc/irq/111/smp_affinity ] && echo 2 > /proc/irq/111/smp_affinity		# USB1.0 2.0 only work on CPU1
#			[ -e /proc/irq/112/smp_affinity ] && echo 2 > /proc/irq/112/smp_affinity		# USB3.0 only work on CPU1
		fi
	;;
	remove)
	;;
	*)
	;;
esac