#!/bin/sh

case "$ACTION" in 
	USB3_RESET) 
	echo "================USB3_RESET==========ACTION :  $ACTION========" >> /dev/console
	rmmod xhci_hcd.ko 
	sleep 1s 
	insmod /lib/modules/2.6.36.4brcmarm/kernel/drivers/usb/host/xhci-hcd.ko 
	;; 
esac
