#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=47

AC_LIBDIR=/lib/access_control

ac() {
	. $AC_LIBDIR/core.sh
	fw_$1
}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	local ap_mode_support=`uci get profile.@access_control[0].ap_mode_support -c "/etc/profile.d"`
	if [ "$sysmode" = "router" ] || [[ "$ap_mode_support" = "yes" -a "$sysmode" = "ap" ]]; then
	ac start
	fi
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	local ap_mode_support=`uci get profile.@access_control[0].ap_mode_support -c "/etc/profile.d"`
	if [ "$sysmode" = "router" ] || [[ "$ap_mode_support" = "yes" -a "$sysmode" = "ap" ]]; then
	ac stop
	fi
}

restart() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	local ap_mode_support=`uci get profile.@access_control[0].ap_mode_support -c "/etc/profile.d"`
	if [ "$sysmode" = "router" ] || [[ "$ap_mode_support" = "yes" -a "$sysmode" = "ap" ]]; then
	ac restart
	fi
}

reload() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	local ap_mode_support=`uci get profile.@access_control[0].ap_mode_support -c "/etc/profile.d"`
	if [ "$sysmode" = "router" ] || [[ "$ap_mode_support" = "yes" -a "$sysmode" = "ap" ]]; then
	ac reload
	fi
}
