#!/bin/sh /etc/rc.common

START=18

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

. /lib/bcmenet/bcmenet_c5400s.sh
. /lib/switch/core_phy.sh

load_bcmenet_driver () {

	# set LAN MAC to RoboSwitch Multiport Address
	#
	# N.B.
	# if we disabled ULF, we must set LAN MAC to RoboSwitch, 
	# either multiport address or static ARL entry.
	# because RoboSwitch default disable learning address from IMP port
	# if we don't add LAN MAC manually to RoboSwitch, 
	# all traffic to CPU will be flooded. 
	#
	local bcmenet_param=""
	local mac=`getfirm MAC`
	if [ $? -eq 0 ] ; then
		bcmenet_param="tp_lanmac=$mac"
	fi
	insmod /lib/modules/*/extra/bcm_enet.ko $bcmenet_param

	insmod /lib/modules/*/extra/bcmmcast.ko

#	insmod /lib/modules/*/extra/bcm_usb.ko
	insmod /lib/modules/*/extra/bcmvlan.ko  
	insmod /lib/modules/*/extra/pwrmngtd.ko  
	
#	insmod /lib/modules/*/extra/otp.ko

#	insmod /lib/modules/*/kernel/net/ipv4/netfilter/nf_nat_ipv4.ko
	insmod /lib/modules/*/kernel/net/ipv4/udp_tunnel.ko
	insmod /lib/modules/*/kernel/net/ipv6/ip6_udp_tunnel.ko
	insmod /lib/modules/*/kernel/net/ipv4/ip_tunnel.ko
#	insmod /lib/modules/*/kernel/net/ipv4/netfilter/nf_nat_masquerade_ipv4.ko
#	insmod /lib/modules/*/kernel/net/netfilter/nf_nat_redirect.ko
#	insmod /lib/modules/*/kernel/net/ipv6/netfilter/nf_reject_ipv6.ko

}

start() {
	# insmod bcm enet releated drivers
	load_bcmenet_driver

	# check switch port ifname
	switch_port_ifname_check

	c5400s_get_interface_group

	power_down_all_ports
	
	#pause_enable_lan_ports
	
	config_if

	c5400s_interface_init_config

	echo "bcmenet Initialize done..." >&2

} 2> /dev/console 1>&2

restart() {
	echo "bcmenet don't support restart" >&2
}

shutdown() {
	echo "bcmenet don't support shutdown" >&2
}

stop() {
	echo "bcmenet don't support stop" >&2
}

reload() {
	echo "bcmenet don't support reload" >&2
}
