#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

. /lib/switch/core_phy.sh

start() {
	bcm_set_cpu_lan_mac
	
	bcm_set_iq

	setup_fc

	setup_all_pause
	
	setup_wan_duplex

	setup_wan_ports

	setup_phy_eee
	
	setup_phy_wirespeed

	power_up_all_ports

	echo "bcm tm init done" > /dev/console
}
