#!/bin/sh /etc/rc.common
# Copyright(c) 2011-2015 Shenzhen TP-LINK Technologies Co.Ltd.

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

START=46


. /lib/functions/powermanager-config.sh

debug() {
    echo $1 >/dev/console 2>&1
}

start() {
        local pro_id=`getfirm PRODUCT_ID`
        if [ "$pro_id" = "15000002" ]; then
                cp /etc/powermanager/powermanager-bcm6750_V2.conf /etc/powermanager.conf
        fi
        prepare_configfil
        service_start /bin/nice -n -20 /usr/sbin/powermanager

        return 0
}

stop() {
        service_stop /usr/sbin/powermanager
        return 0
}

reload() {
    return 0
}
