#!/bin/sh /etc/rc.common

START=90
STOP=90

#USE_PROCD=1

#set -x

local smart_home_schedule_cron_cmd="0-59\/1 \* \* \* \* \/usr\/sbin\/smart_home_schedule"
start() {
        reload
}

reload() {
        echo "smart_home_schedule reload_service" > /dev/console
        config_load smart_home
        maclist_smart_home=""
        config_foreach getmaclist_sec client
        echo "maclist_smart_home:$maclist_smart_home" > /dev/console

        # add by DengZhong AP mode(ebtables) Router Mode(iptables)
        local sysmode="$(uci get sysmode.sysmode.mode)"
        if [ "${sysmode}" != "router" ]; then
                echo "### smart_home_schedule is NOT ready for other mode yet###" > /dev/console
                return
        fi

        setpauselistiptables
    	updateneighlist
}

getmaclist_sec() {
        local section="$1"
        config_get mac "$section" mac
        mac=${mac//-/:}

        config_get cause "$section" cause
        if [ -n "$cause" ]; then
                append maclist_smart_home "$mac "
        fi
}

setpauselistiptables() {
        iptables -N pauselist

        iptables -D FORWARD -j pauselist
        iptables -I FORWARD 2 -j pauselist

        iptables -D input_rule -j pauselist
        iptables -I input_rule 1 -j pauselist

        iptables -F pauselist

        if [ ! -n "$maclist_smart_home" ]; then
                echo "#### no schedule client found in blacklist config ####" > /dev/console
        fi

        echo "Call smart_home_schedule and add it to crontabs" > /dev/console

        local CRON_FILE="/etc/crontabs/root"
        local TMP_CRONTAB="/tmp/smart_home_cron"
        local SMART_HOME_BIN="/usr/sbin/smart_home_schedule"

        if [ ! -f "$CRON_FILE" ]; then
                touch $CRON_FILE
                chmod 777 $CRON_FILE
        fi

        echo "start crond..." > /dev/console

        local new_cron_item="0-59/1 * * * * ${SMART_HOME_BIN}"
        cron_item=`grep "${SMART_HOME_BIN}" ${CRON_FILE}`
        [ "${cron_item}" != "${new_cron_item}" ] && {
                        echo "${new_cron_item}" > ${TMP_CRONTAB}
                        crontab -l | grep -v "${SMART_HOME_BIN}" | cat - "${TMP_CRONTAB}" | crontab -
                        rm -f ${TMP_CRONTAB}
        }

        ${SMART_HOME_BIN} first
}

updateneighlist() {
        [ -n "$maclist_smart_home" ] && {

        for mac in $maclist_smart_home; do
        ips=$(cat /proc/net/arp | grep -i "$mac" | awk '{print $1}')
        [ -n "$ips" ] && {
            for ip in $ips; do
                conntrack -D -s "$ip"
                conntrack -D -d "$ip"
                ip neigh del $ip dev br-lan
#               ip neigh del $ip dev br-guest
            done
        }
        done;
        }
}
