#!/bin/sh /etc/rc.common

START=50

SERVICE_DAEMONIZE=1
start()
{
	echo "[tdpServer exec] === start ==="
	echo "[tdpServer exec] === check if tdpServer exists ==="
	local tdpserver=$(pgrep tdpServer| wc -l)
	if [ "$tdpserver" -ge 1 ]; then
		echo "[tdpServer exec] === tdpServer exists, just return ==="
		return 1
	fi
	"/bin/nice" -n -5 /usr/bin/tdpServer &>/dev/null &
	echo "[tdpServer exec] === start end ==="
}

stop()
{
	echo "[tdpServer exec] === stop ==="
	local tdpServer_pid=`pgrep /usr/bin/tdpServer`

	if [ -n "$tdpServer_pid" ];then
		for pid in $tdpServer_pid; do
			kill -9 "$pid"
		done
	fi

	echo "[tdpServer exec] === stop end ==="
}

restart()
{
	stop
	sleep 1
	start
}
