#!/bin/sh /etc/rc.common

START=77
STOP=77

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

TFSTATS_MOD_ID=269
LOG_INF_SERVICE_START=504
LOG_INF_SERVICE_STOP=505

start() {
	local enable
	config_load tfstats
	
	config_get enable "switch" enable
	if [ "$enable" = "on" ]; then
		# NOTICE: AX6000 $(uname -r) is 4.1.51, but doesn't has this Runner bug
		# REMOVE this when BCM fix Runner bug
	  	# if [ -f /lib/modules/4.1.27/extra/pktrunner.ko ] ; then
		# 	rmmod pktrunner
		# fi
		[ -f /sys/sfe_ipv4/tfstats ] && echo 1 > /sys/sfe_ipv4/tfstats
	fi

	if [ ! -f /var/run/tfstats.pid ] ; then
		service_start /usr/sbin/tfstats $enable
		echo $! > /var/run/tfstats.pid
		logx -p $$ $TFSTATS_MOD_ID $LOG_INF_SERVICE_START
	elif [ "$enable" = "on" ]; then
		ubus call tfstats on
	fi


	## sync hnat status
	[ -x "/usr/sbin/sync_hnat_status" ] && /usr/sbin/sync_hnat_status

	return 0
}

stop() {
	ubus call tfstats off
	[ -f /sys/sfe_ipv4/tfstats ] && echo 0 > /sys/sfe_ipv4/tfstats

	## sync hnat status
	[ -x "/usr/sbin/sync_hnat_status" ] && /usr/sbin/sync_hnat_status

	# For AX6000/AX11000, should keep tfstat on, show traffic instead of TM modules 
	#ubus call tfstats off
	#if [ -f /lib/modules/4.1.27/extra/pktrunner.ko ] ; then
        #      insmod /lib/modules/4.1.27/extra/pktrunner.ko || true
	#fi
	#local pid
	#pid=$(cat /var/run/tfstats.pid)
	#kill -9 $pid
	logx -p $$ $TFSTATS_MOD_ID $LOG_INF_SERVICE_STOP
	return 0
}
