#!/bin/sh /etc/rc.common
# Copyright(c) 2011-2019 Shenzhen TP-LINK Technologies Co.Ltd.
# file     vpn.init
# brief    
# author   Zhu Haiming
# version  1.0.0
# date     8Apr19
# histry   arg 1.0.0, 8Apr19, Zhu Haiming, Create the file. 

START=90

vpn() {
	. /lib/vpn/vpn_core.sh
	vpn_$1 $2

}

start() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		vpn start $1
	fi
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		vpn stop $1
	fi
}

restart() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		vpn restart $1
	fi
}

reload() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "router" ]; then
		vpn reload $1
	fi
}

