#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

TMP_FILE_PORT="/tmp/v6plus/v6plus_port"
local wanproto=$(uci get network.wan.wan_type)
local peeraddr=$(uci get network.wan.localIPAddress)

[ "$ACTION" = "start" ] && [ "$wanproto" = "v6plus" ] && [ -n "$peeraddr" ] && {
	local fakeip="192.0.0.1"

	iptables -t nat -N v6plus_checkports
	
	iptables -t nat -D zone_lan_prerouting -j v6plus_checkports
	iptables -t nat -A zone_lan_prerouting -j v6plus_checkports
	
	iptables -t nat -F v6plus_checkports
	iptables -t nat -I v6plus_checkports -p tcp -j CHECKPORTS --param ${peeraddr}-${fakeip}:${TMP_FILE_PORT}
	iptables -t nat -I v6plus_checkports -p udp -j CHECKPORTS --param ${peeraddr}-${fakeip}:${TMP_FILE_PORT}
	iptables -t nat -I v6plus_checkports -p icmp -j CHECKPORTS --param ${peeraddr}-${fakeip}:${TMP_FILE_PORT}
	
	iptables -t nat -N v6plus_output
	iptables -t nat -D zone_wan_nat -j v6plus_output
	iptables -t nat -I zone_wan_nat -j v6plus_output
	iptables -t nat -F v6plus_output
	iptables -t nat -I v6plus_output -p tcp --sport 1:65535 -j V6PORTS --to-source ${peeraddr}:${TMP_FILE_PORT}
	iptables -t nat -I v6plus_output -p udp --sport 1:65535 -j V6PORTS --to-source ${peeraddr}:${TMP_FILE_PORT}
	iptables -t nat -I v6plus_output -p icmp -j V6PORTS --to-source ${peeraddr}:${TMP_FILE_PORT}
}