#!/bin/sh

. /lib/functions.sh

if [ "$ACTION" != "start"  ]; then
	exit 0
fi

openvpn_handle()
{
	local enabled="off"
	local proto="udp"
	local port="1194"
	local access="home"

	config_load openvpn
	config_get enabled "server" "enabled"
	config_get proto "server" "proto"
	config_get port "server" "port"
	config_get access "server" "access"

    # add rules back here
    # fw will skip existing ones
	if [ "$enabled" = "on" ]; then
		fw openvpn_access $proto $port $access
	fi
}

pptpvpn_handle()
{
	local enabled="off"

	config_load pptpd
	config_get enabled "pptpd" "enabled"
	config_get smbacc  "pptpd" "samba_access"

    # add rules back here
    # fw will skip existing ones
	if [ "$enabled" = "on" ]; then
		fw pptp_access $smbacc
	fi
}

l2tpvpn_handle()
{
	local enabled="off"

	config_load l2tpoveripsec
	config_get enabled "l2tpoveripsec" "enabled"
	config_get encryption "l2tpoveripsec" "encryption"

	if [ "$enabled" != "on" ]; then
		return 0;
	fi
	if [ "$encryption" = "true" ]; then
		/etc/init.d/ipsec restart
	fi
	/etc/init.d/xl2tpd restart

}

vpn_client_handle()
{
	#/etc/init.d/vpnc restart
#make sure vpnc-related iptables rules exist, cause certain apps could FLUSH all chains in certain table
	echo "=================$0==============" > /dev/console
	. /lib/vpn/vpn_core.sh
	vpn_check_add_rules
}

vpn_client_handle
l2tpvpn_handle
openvpn_handle
pptpvpn_handle
