#!/bin/sh

local model=`getfirm MODEL`

if [ "$model" == "Archer AX1500" ] ; then
	uci set locale.sysinfo.model="AX1500 Wi-Fi 6 Router"
	echo locale.sysinfo.model="AX1500 Wi-Fi 6 Router" > /dev/console
elif [ "$model" == "Archer AX1450" ] ; then
	uci set locale.sysinfo.model="AX1450 Wi-Fi 6 Router"
	echo locale.sysinfo.model="AX1450 Wi-Fi 6 Router" > /dev/console
fi

uci commit
