#!/bin/sh

if [ "$(nvram kget rftestflag)" == "1" ]; then
	rmmod wl
	rmmod igs
	rmmod emf
	rmmod hnd
	nvram set txlauncher_flag=1
	nvram kset rftestflag=0
	nvram unset wl0_vifs
	nvram unset wl1_vifs
	wifi start
fi
