#!/usr/bin/lua

--this file called in nvrmamanager after firmware up ok
local uci_r = require("luci.model.uci").cursor()
local sys = require "luci.sys"
local auto_update_support = uci_r:get_profile("firmware_upgrade", "auto_update_support") or "no"
if auto_update_support == "yes" then
	uci_r:set("auto_upgrade", "upgrade", "cloud_push", "0")
	uci_r:set("auto_upgrade", "upgrade", "delay", '0')
	uci_r:commit("auto_upgrade")
end
uci_r:delete("cloud_config", "new_firmware")
uci_r:delete("cloud_config", "upgrade_info")
uci_r:set("cloud_config", "new_firmware", "cloud_push")
uci_r:set("cloud_config", "upgrade_info", "cloud_reply")
uci_r:set("cloud_config", "info", "show_flag", "0")
uci_r:set("cloud_config", "info", "tcsp_status", "1")
uci_r:commit("cloud_config")

sys.fork_call(". /lib/wportal/wportal.sh && wportalctrl_clear_upgrade_mac")
