#!/bin/sh

local in_lan_status=""
local wan_status=""
local in_lan_speed=""
local wan_speed=""
local speeds=""
local wan_duplex=""
local in_lan_duplex=""
local duplexs=""
local wan_ifname=""
local lan_ifnames=""

append_status()
{
	eval $1=\"\$$1' '$2\"
}

# usage: get_port_speed $var_name $dev_name
get_port_speed()
{
	local var_name=$1
	local dev_name=$2
	
	local speed=$(ethctl $dev_name media-type | grep -i " Up " | egrep -o "[0-9\.]+.")
	if [ -n "$speed" ]
	then
		case $speed in
		"2.5G")
			speed="2500"
			;;
		"1G")
			speed="1000"
			;;
		"1000M")
			speed="1000"
			;;
		"100M")
			speed="100"
			;;
		"10M")
			speed="10"
			;;
		*)
			echo "bad port speed: $speed"
			speed="0"
			;;
		esac
		
		append_status "$var_name" "$speed"
	else
		append_status "$var_name" "0"
	fi
}

# usage: get_port_status $var_name $dev_name
get_port_status()
{
	local var_name=$1
	local dev_name=$2
	
	ethctl $dev_name media-type | grep -iq " Up "
	if [ $? -eq 0 ]; then
		append_status "$var_name" "connected"
	else
		append_status "$var_name" "unconnected"
	fi
}

# usage: get_port_status $var_name $dev_name
get_port_duplex()
{
	local var_name=$1
	local dev_name=$2
	
	local duplex=$(ethctl $dev_name media-type | grep -i " Up " | egrep -io "duplex:.*"| awk '{print $2}')
	if [ -n "$duplex" ]
	then
		if [ "$duplex" == "FD" ]
		then
			append_status "$var_name" "FULL"
		else
			append_status "$var_name" "HALF"
		fi
	else
		append_status "$var_name" "NONE"
	fi
}

get_lan_status()
{
	for ifname in ${lan_ifnames}
	do
		get_port_status "in_lan_status" "$ifname"
	done		
}

get_lan_speed()
{	
	for ifname in ${lan_ifnames}
	do
		get_port_speed "in_lan_speed" "$ifname"
	done	
}

get_lan_duplex()
{
	for ifname in ${lan_ifnames}
	do
		get_port_duplex "in_lan_duplex" "$ifname"
	done	
}

get_wan_speed()
{
	get_port_speed wan_speed $wan_ifname
}

get_wan_status()
{
	get_port_status wan_status $wan_ifname
}

get_wan_duplex()
{
	get_port_duplex wan_duplex $wan_ifname
}

get_port_state()
{
	local sec_name=$1
	local dev_name=$(uci get switch.${sec_name}.ifname)
	ethctl ${dev_name} media-type | grep -iq " Up "
	echo $?
}

get_lan_wan_ifnames()
{
    local wan_sec=$(uci get switch.wan.switch_port)
    wan_ifname=$(uci get switch.${wan_sec}.ifname)

    lan_ifnames=""
    local lan4_sec=$(uci get switch.lan4.switch_port)
    local lan_list="lan1 lan2 lan3 ${lan4_sec}"
    for lan in ${lan_list}
    do
        local ifname=$(uci get switch.${lan}.ifname)
        [ -n "${lan_ifnames}" ] && lan_ifnames="${lan_ifnames} "
        lan_ifnames="${lan_ifnames}${ifname}"
    done

    #echo "wan_ifname: $wan_ifname" >/dev/console
    #echo "lan_ifnames: $lan_ifnames" > /dev/console
}

get_lan_wan_ifnames
case $1 in
	"lan_status")
		get_lan_status
		echo -n $in_lan_status 
		;;
	"lan_speed")
		get_lan_speed
		echo -n $in_lan_speed
		;;
	"wan_status")
		get_wan_status 
		echo -n $wan_status
		;;
	"wan_speed")
		get_wan_speed
		echo -n $wan_speed
		;;
	"lan_duplex")
		get_lan_duplex
		echo -n $in_lan_duplex
		;;
	"wan_duplex")
		get_wan_duplex
		echo -n $wan_duplex
		;;
	"speed")
		get_wan_speed
		get_lan_speed
		echo -n $wan_speed $in_lan_speed
		;;
	"duplex")
		get_wan_duplex
		get_lan_duplex
		echo -n $wan_duplex $in_lan_duplex
		;;
	"port_state")
		shift
		echo -n $(get_port_state $@)
		;;
	*)
		echo "bad choice"
		;;
esac
