#!/bin/sh

. /lib/functions.sh

config_load network
config_get proto internet proto "none"

if [[ "$proto" != "none" && "$INTERFACE" == "internet" ]]; then
	config_get mtu internet mru
elif [[ "$proto" == "none" && "$INTERFACE" == "wan" ]]; then
	config_get mtu wan mtu
else
	exit 0
fi

if [[ "$ACTION" == "ifup" ]]; then
	# fw unsetmss
	fw setmss $((mtu-40))

	local wanproto=$(uci get network.wan.wan_type)
	[ "$wanproto" = "dslite" -o "$wanproto" = "v6plus" ] && {
		fw s_add 4 m OUTPUT zone_wan_MSSFIX ^
	}
elif [[ "$ACTION" == "ifdown" ]]; then
	fw unsetmss
	fw s_del 4 m OUTPUT zone_wan_MSSFIX
fi

exit 0
